name: discord_storage
description: A CLI tool for storing large files on Discord using a bot
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0

executables:
  discord_storage: